# -*- coding: utf-8 -*-
"""CalculusHW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbHMOVfitREK0gfn6YgDp6P2MNS8RpGy

__1.__ Найти производную функции:

### $$y=\frac{1}{x}+\frac{2}{x^2}-\frac{5}{x^3}+\sqrt x -\sqrt[3]x+\frac{3}{\sqrt x}$$

$$\Big(\frac{1}{x}\Big)' = (x^{-1})'=-x^{-2}$$
$$\Big(\frac{2}{x^2}\Big)' = (2x^{-2})'=2(-2)x^{-3}=-4x^{-3}$$
$$\Big(-\frac{5}{x^3}\Big)' = (-5x^{-3})'=-5(-3)x^{-4}=15x^{-4}$$
$$(\sqrt x)' = (x^{\frac{1}{2}})'=\frac{1}{2}x^{-\frac{1}{2}}=\frac{1}{2}\frac{1}{\sqrt x}$$
$$(-\sqrt[3] x)' = (-x^{\frac{1}{3}})'=-\frac{1}{3}x^{-\frac{2}{3}}=-\frac{1}{3}\frac{1}{\sqrt[3] {x^2}}$$
$$(\frac{3}{\sqrt x})' = (3x^{-\frac{1}{2}})'=3(-\frac{1}{2})x^{-\frac{3}{2}}=(-\frac{3}{2})x^{-\frac{3}{2}}=-\frac{3}{2}\frac{1}{\sqrt {x^3}}$$
$$y'=-\frac{1}{x^{2}}-\frac{4}{x^3}+\frac{15}{x^4}+\frac{1}{2}\frac{1}{\sqrt x}-\frac{1}{3}\frac{1}{\sqrt[3] {x^2}}-\frac{3}{2}\frac{1}{\sqrt {x^3}}=-x^{-2}-4x^{-3}+15x^{-4}+\frac{1}{2}x^{-\frac{1}{2}} -\frac{1}{3}x^{-\frac{2}{3}}-\frac{3}{2}x^{-\frac{3}{2}}$$
"""

from sympy import *
init_printing()

x = Symbol('x')
#f = ((1/x)+(2/(x^2))-(5/(x^3))+(x^(1/2))-(x^(1/3))+(3/(x^(1/2))))
f = (1/x)+(2/(x**2))-(5/(x**3))+(x**(1/2))-(x**(1/3))+(3/(x**(1/2)))
diff(f, x)

"""__2.__ Найти производную функции:

### $$y=x \cdot \sqrt {1+x^2}$$
$$(x \cdot \sqrt {1+x^2})' = 1\cdot\sqrt {1+x^2}+x\cdot(\sqrt {1+x^2})'= \sqrt {1+x^2}+x\cdot\frac{1}{2}\Big(\frac{1}{\sqrt {1+x^2}}\Big)\cdot 2x = \sqrt {1+x^2}+\frac{x^2}{\sqrt {1+x^2}} = \frac{1+x^2+x^2}{\sqrt {1+x^2}} = \frac{2x^2+1}{\sqrt {1+x^2}}$$
"""

x = Symbol('x')
#f = (x*((x**2+1)**(1/2)))
f = x*sqrt(x**2 + 1)
diff(f, x)

"""__3.__ Найти производную функции:

### $$y= \frac{2x}{1-x^2}$$
$$\Big( \frac{2x}{1-x^2}\Big)'=\frac{2\cdot(1-x^2)-2x(-2x)}{(1-x^2)^2}=\frac{2\cdot(1-x^2)+4x^2}{(1-x^2)^2} = \frac{2-2x^2+4x^2}{(1-x^2)^2} =\frac{2x^2+2}{(1-x^2)^2}$$
"""

x = Symbol('x')
f = 2*x/(1-x**2)
diff(f, x)

"""__4*.__ Найти производную функции:

### $$y=\sqrt{x+ \sqrt{x+\sqrt x}}$$

$$\Big(\sqrt{x+ \sqrt{x+\sqrt x}}\Big)'=\Big(\Big(x+\Big(x+x^{\frac{1}{2}}\Big)^{\frac{1}{2}}\Big)^{\frac{1}{2}}\Big)' = \frac{1}{2}\frac{1}{x + \sqrt{x+\sqrt{x}}}\cdot\Big(x+(x+x^{\frac{1}{2}})^\frac{1}{2}\Big)'=\frac{1}{2}\frac{1}{x + \sqrt{x+\sqrt{x}}}\cdot\Big(1+\Big((x+x^{\frac{1}{2}})^\frac{1}{2}\Big)'\Big)=\frac{1}{2}\frac{1}{x + \sqrt{x+\sqrt{x}}}\cdot\Big(1+\frac{1}{2}\frac{1}{\sqrt{x+\sqrt x}}\Big(x+x^{\frac{1}{2}}\Big)'\Big)=\frac{1}{2}\frac{1}{x + \sqrt{x+\sqrt{x}}}\cdot\Big(1+\frac{1}{2}\frac{1}{\sqrt{x+\sqrt x}}\Big(1+\frac{1}{2}x^{-\frac{1}{2}}\Big)\Big)=\frac{1}{2}\frac{1}{x + \sqrt{x+\sqrt{x}}}\cdot\Big(1+\frac{1}{2}\frac{1}{\sqrt{x+\sqrt x}}\Big(1+\frac{1}{2}\frac{1}{\sqrt x}\Big)\Big)\frac{1}{2}\Big(x+\Big(x+x^{\frac{1}{2}}\Big)^{\frac{1}{2}}\Big)^{-\frac{1}{2}}\cdot\Big(1+\frac{1}{2}\Big(x+x^{\frac{1}{2}}\Big)^{-\frac{1}{2}}\cdot \Big(1+\frac{1}{2}x^{-\frac{1}{2}}\Big)\Big)$$
"""

x = Symbol('x')
#f = (x+(x+x**(1/2))**(1/2))**(1/2)
f = sqrt(x+sqrt(x+sqrt(x)))
f

diff(f, x)

"""__5.__ Найти производную функции:

### $$y= \ln(x+\sqrt{x^2+1})$$

$$(\ln(x+\sqrt{x^2+1}))'=\frac{1}{x+\sqrt{x^2+1}}\cdot \Big(x+\sqrt{x^2+1} \Big)'=\frac{1}{x+\sqrt{x^2+1}}\cdot \Big(1+\frac{1}{2}\frac{2x}{\sqrt{x^2+1}} \Big)=\frac{1}{x+\sqrt{x^2+1}}\cdot \Big(1+\frac{x}{\sqrt{x^2+1}} \Big)=\frac{1}{x+\sqrt{x^2+1}}\cdot \frac{x+\sqrt{x^2+1}}{\sqrt{x^2+1}}=\frac{1}{\sqrt{x^2+1}}$$
"""

x = Symbol('x')
#f = (x+(x+x**(1/2))**(1/2))**(1/2)
f = ln(x+sqrt(x**2+1))
f

diff(f, x)

"""__6.__ Найти производную функции:

### $$y=x \cdot \ln(x+\sqrt{x^2+1})-\sqrt{x^2+1}$$

$$(x\cdot\ln(x+\sqrt{x^2+1}))' = \ln(x+\sqrt{x^2+1})+x\cdot(\ln(x+\sqrt{x^2+1}))')= \ln(x+\sqrt{x^2+1})+x\frac{1}{x+\sqrt{x^2+1}}\cdot(x+\sqrt{x^2+1})')= \ln(x+\sqrt{x^2+1})+\frac{x}{x+\sqrt{x^2+1}}\cdot\Big(1+\frac{1}{2}\frac{1}{\sqrt{x^2+1}}\cdot(x^2+1)'\Big)= \ln(x+\sqrt{x^2+1})+\frac{x}{x+\sqrt{x^2+1}}\cdot\Big(1+\frac{1}{2}\frac{1}{\sqrt{x^2+1}}\cdot2x\Big)=\ln(x+\sqrt{x^2+1})+\frac{x}{x+\sqrt{x^2+1}}\cdot\Big(1+\frac{x}{\sqrt{x^2+1}}\Big)=\ln(x+\sqrt{x^2+1})+\frac{x}{x+\sqrt{x^2+1}}\cdot\Big(\frac{\sqrt{x^2+1}+x}{\sqrt{x^2+1}}\Big)=\ln(x+\sqrt{x^2+1})+\frac{x}{\sqrt{x^2+1}}$$
$$(\sqrt{x^2+1})'=\frac{1}{2}\frac{2x}{\sqrt{x^2+1}}=\frac{x}{\sqrt{x^2+1}}$$

 $$ (x\ln(x+\sqrt{x^2+1})-\sqrt{x^2+1})' = \ln(x+\sqrt{x^2+1})+\frac{x}{\sqrt{x^2+1}} - \frac{x}{\sqrt{x^2+1}} = \ln(x+\sqrt{x^2+1})$$
"""

x = Symbol('x')
#f = (x+(x+x**(1/2))**(1/2))**(1/2)
f = x*ln(x+sqrt(x**2+1))-sqrt(x**2+1)
f

diff(f, x)

"""__7*.__ Найти производную функции:

### $$y=\arcsin (\sin x)$$

$$y=\arcsin (\sin x) = \arcsin (\sin x)'*(\sin x)'= \frac{1}{\sqrt{{1-(\sin x)^2}}}*(\cos x) = \frac{\cos x}{|\cos x|}$$

Производная неопределена при cos(x) = 0. Т.е. при $x = \pi/2+k*\pi$. Это будут экстремумы графика arcsin.

8*. Вычислить приближенное значение:

$\sin(1^0)=\sin(\frac{\pi}{180})$



$$f(x+\Delta x) \approx f(x)+f'(x) \cdot \Delta x$$
$$$$
$$\sin (1^0)= \sin(0^0 + 1^0)$$
$$$$
$$x = 1^0, x_0=0^0$$
$$$$
$$\Delta x = 1^0 - 0^0 = 1^0=\frac{\pi}{180^0}$$
$$$$
$$\sin(1^0) \approx \sin(0^0)+\cos(0^0)\cdot\Big(\frac{\pi}{180^0}\Big)=1*\Big(\frac{3.14}{180}\Big)=0,017(4)$$

$\sin(0.1^0)=\sin(0^0+0.1^0)$
$$\Delta x = 0.1^0 - 0^0 = 0.1^0=0.1*\frac{\pi}{180}=0.00174533$$
$$$$
$$\sin(1^0) \approx \sin(0^0)+\cos(0^0)\cdot\Big(\frac{\pi}{180^0}\Big)=\Big(\frac{0.1*3.14}{180}\Big)=0.0017(4)$$

__9**.__ Написать на python алгоритм, по вычислению значений $\sin(x)$ для $х \in[0, 30^0]$

Для проверки подойдут данные из таблицы Брадиса
"""

import numpy as np

sinuses = np.zeros((31,11))
x = np.arange(11)*0.1

for i in range(0, 31):
  for j in range(0, 11):
    sinuses[i][j] = round((i + x[j])*3.1415/180, 4)

print(sinuses)

"""Таблица Брадиса"""

bradis = np.array([[0.0000, 0.0017, 0.0035, 0.0052, 0.0070, 0.0087, 0.0105, 0.0122, 0.0140, 0.0157, 0.0175]])
str1 = [0.0175, 0.0192, 0.0209, 0.0227, 0.0244, 0.0262, 0.0279, 0.0297, 0.0314, 0.0332, 0.0349]
str2 = [0.0349, 0.0366, 0.0384, 0.0401, 0.0419, 0.0436, 0.0454, 0.0471, 0.0488, 0.0506, 0.0523]
str3 = [0.0523, 0.0541, 0.0558, 0.0576, 0.0593, 0.0610, 0.0628, 0.0645, 0.0663, 0.0680, 0.0698]
str4 = [0.0698, 0.0715, 0.0732, 0.0750, 0.0767, 0.0785, 0.0802, 0.0819, 0.0837, 0.0854, 0.0872]
str5 = [0.0872, 0.0889, 0.0906, 0.0924, 0.0941, 0.0958, 0.0976, 0.0993, 0.1011, 0.1028, 0.1045]
str6 = [0.1045, 0.1063, 0.1080, 0.1097, 0.1115, 0.1132, 0.1149, 0.1167, 0.1184, 0.1201, 0.1219]
str7 = [0.1219,	0.1236,	0.1253,	0.1271,	0.1288,	0.1305,	0.1323,	0.1340,	0.1357,	0.1374,	0.1392]
str8 = [0.1392,	0.1409,	0.1426,	0.1444,	0.1461,	0.1478,	0.1495,	0.1513,	0.1530,	0.1547,	0.1564]
str9 = [0.1564,	0.1582,	0.1599,	0.1616,	0.1633,	0.1650,	0.1668,	0.1685,	0.1702,	0.1719,	0.1736]
str10 =	[0.1736,	0.1754,	0.1771,	0.1788,	0.1805,	0.1822,	0.1840,	0.1857,	0.1874,	0.1891,	0.1908]
str11 =	[0.1908,	0.1925,	0.1942,	0.1959,	0.1977,	0.1994,	0.2011,	0.2028,	0.2045,	0.2062,	0.2079]
str12 =	[0.2079,	0.2096,	0.2113,	0.2130,	0.2147,	0.2164,	0.2181,	0.2198,	0.2215,	0.2233,	0.2250]
str13 =	[0.2250,	0.2267,	0.2284,	0.2300,	0.2317,	0.2334,	0.2351,	0.2368,	0.2385,	0.2402,	0.2419]
str14	= [0.2419,	0.2436,	0.2453,	0.2470,	0.2487,	0.2504,	0.2521,	0.2538,	0.2554,	0.2571,	0.2588]
str15	= [0.2588,	0.2605,	0.2622,	0.2639,	0.2656,	0.2672,	0.2689,	0.2706,	0.2723,	0.2740,	0.2756]
str16	= [0.2756,	0.2773,	0.2790,	0.2807,	0.2823,	0.2840,	0.2857,	0.2874,	0.2890,	0.2907,	0.2924]
str17	= [0.2942,	0.2940,	0.2957,	0.2974,	0.2990,	0.3007,	0.3024,	0.3040,	0.3057,	0.3074,	0.3090]
str18	= [0.3090,	0.3107,	0.3123,	0.3140,	0.3156,	0.3173,	0.3190,	0.3206,	0.3223,	0.3239,	0.3256]
str19	= [0.3256,	0.3272,	0.3289,	0.3305,	0.3322,	0.3338,	0.3355,	0.3371,	0.3387,	0.3404,	0.3420]
str20	= [0.3420,	0.3437,	0.3453,	0.3469,	0.3486,	0.3502,	0.3518,	0.3535,	0.3551,	0.3567,	0.3584]
str21	= [0.3584,	0.3600,	0.3616,	0.3633,	0.3649,	0.3665,	0.3681,	0.3697,	0.3714,	0.3730,	0.3746]
str22	= [0.3746,	0.3762,	0.3778,	0.3795,	0.3811,	0.3827,	0.3843,	0.3859,	0.3875,	0.3891,	0.3907]
str23	= [0.3097,	0.3923,	0.3939,	0.3955,	0.3971,	0.3987,	0.4003,	0.4019,	0.4035,	0.4051,	0.4067]
str24	= [0.4067,	0.4083,	0.4099,	0.4115,	0.4131,	0.4147,	0.4163,	0.4179,	0.4195,	0.4210,	0.4226]
str25	= [0.4226,	0.4242,	0.4258,	0.4274,	0.4289,	0.4305,	0.4321,	0.4337,	0.4352,	0.4368,	0.4384]
str26	= [0.4384,	0.4399,	0.4415,	0.4431,	0.4446,	0.4462,	0.4478,	0.4493,	0.4509,	0.4524,	0.4540]
str27	= [0.4540,	0.4555,	0.4571,	0.4586,	0.4602,	0.4617,	0.4633,	0.4648,	0.4664,	0.4679,	0.4695]
str28	= [0.4695,	0.4710,	0.4726,	0.4741,	0.4756,	0.4772,	0.4787,	0.4802,	0.4818,	0.4833,	0.4848]
str29	= [0.4848,	0.4863,	0.4879,	0.4894,	0.4909,	0.4924,	0.4939,	0.4955,	0.4970,	0.4985,	0.5000]
str30	= [0.5000,	0.5015,	0.5030,	0.5045,	0.5060,	0.5075,	0.5090,	0.5105,	0.5120,	0.5135,	0.5150]


bradis = np.vstack([bradis, str1])
bradis = np.vstack([bradis, str2])
bradis = np.vstack([bradis, str3])
bradis = np.vstack([bradis, str4])
bradis = np.vstack([bradis, str5])
bradis = np.vstack([bradis, str6])
bradis = np.vstack([bradis, str7])
bradis = np.vstack([bradis, str8])
bradis = np.vstack([bradis, str9])
bradis = np.vstack([bradis, str10])
bradis = np.vstack([bradis, str11])
bradis = np.vstack([bradis, str12])
bradis = np.vstack([bradis, str13])
bradis = np.vstack([bradis, str14])
bradis = np.vstack([bradis, str15])
bradis = np.vstack([bradis, str16])
bradis = np.vstack([bradis, str17])
bradis = np.vstack([bradis, str18])
bradis = np.vstack([bradis, str19])
bradis = np.vstack([bradis, str20])
bradis = np.vstack([bradis, str21])
bradis = np.vstack([bradis, str22])
bradis = np.vstack([bradis, str23])
bradis = np.vstack([bradis, str24])
bradis = np.vstack([bradis, str25])
bradis = np.vstack([bradis, str26])
bradis = np.vstack([bradis, str27])
bradis = np.vstack([bradis, str28])
bradis = np.vstack([bradis, str29])
bradis = np.vstack([bradis, str30])

#print(bradis)

print(sinuses-bradis)

"""Видно, что ошибка начинает возрастать при больших углах.

Либо короткий вариант.
"""

import math 

for i in range(0,31,1):
     x = math.radians(i) 
     y = math.sin(x)
     z = i*3.1415/180
     print("PC sin", i ,":", y, 'Derivative sin:', i, z, 'Разность', z - y)